version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - ${ZOOKEEPER_PORT}:2181
    hostname: zookeeper
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    command: [start-kafka.sh]
    ports:
      - ${KAFKA_PORT}:9092
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST_NAME}
      KAFKA_ADVERTISED_PORT: ${KAFKA_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
