package main

import (
	"os"

	"github.com/danielbintar/angel/server-library/migration"
)

func main() {
	var query string
	if len(os.Args) == 2 && os.Args[1] == "down" {
		query = "DROP TABLE IF EXISTS users"
	} else {
		query = `CREATE TABLE IF NOT EXISTS users (
		id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		username VARCHAR(255) NOT NULL,
		password VARCHAR(255) NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		deleted_at TIMESTAMP
		)`
	}

	migration.RunPostgres(&migration.PostgresQueryOpt{Query: query})
}
